### ISSUE TITLE
Cannot export "only" output tree to file

### ISSUE THREAD

**Issue by stitam** [computations/root_digger#16]
I would like to be able to export a file which only contains the output tree so I can easily pipe it into other tools in my workflow.

When I run root digger it prints a log and the output tree to the console. I can direct `stdout` to a file but then the file will contain both the log and the tree. I tried `--silent` which moved things in the right direction but the tool still returned `[0.02] INFO: Early stop is enabled` as well. Ideally I wouldn't want to use `--silent` because I would like to see the log. I also looked for something like `--outfile` in the options but couldn't find anything. Any ideas how I could export the tree? Many thanks.

**Comment by computations** [comment]
There is a file (two actually) which contain what you are looking for. The first is `treename.lwr.tree` which contains the results of the exhaustive search (if enabled). The second is `treename.rooted.tree`, which is just the tree, rooted by the best root. You don't need to specify an outfile, because rootdigger uses the treefile as a prefix for all of its output files (and the checkpoint file).

**Comment by stitam** [comment]
Thanks @computations. I don't see any output files, hm.. Could this be a container thing?

This is the command I used:
`singularity exec stitam-root_digger-1.7.0.img rd --msa polymorphic_sites.fasta --tree tree.tre`

I tried binding my `home` to ensure this is not a mounting issue, but I get the same result, tree in console, no output files.

**Comment by computations** [comment]
It is almost surely a container issue. I personally have never used `singularity`, but when I use rootdigger like

```
sudo docker run -v $(pwd):/data/ my_rd:latest --msa /data/data.phy --tree /data/tree.nwk --exhaustive
```

I get `tree.nwk.lwr.tree` and `tree.nwk.rooted.tree` in the same directory as the data file. My only guess from here is that singularity is doing some magic, but I don't have any experience here.

**Comment by stitam** [comment]
Found the files! I was expecting them in the working directory root, but instead they were placed in the directory where the input tree was located. This is a problem for me because the workflow manager I use for connecting the tools expects the output file to be in the working directory. Is there any way to solve this, apart from moving the input tree into the working directory?

**Comment by computations** [comment]
Beyond dirty filesystem tricks, probably not. Give me a bit and I'll add an option to specify a prefix.

**Comment by computations** [comment]
correction: the prefix option already exists. It's kinda jankey, because c++ doesn't have a good way of making sure that a directory exists in a platform independent way. This means that if the prefix is something like `foo/bar/baz` and either `foo` or `bar` doesn't exist, the program will fail with pretty obtuse error. I'm going to work on making it less jankey, but you can use this for now.

**Comment by stitam** [comment]
`singularity exec stitam-root_digger-1.7.0.img rd --msa polymorphic_sites.fasta --tree tree.tre --prefix rootdig`

creates the files `rootdig.ckp` and `rootdig.rooted.tree` in the working directory. Problem solved, many thanks @computations! A small note, while `--prefix` is listed in `--help`, it is not yet listed in `README.md`.

**Comment by computations** [comment]
Alright, there is a new version that should be a bit better regarding the prefix option. Please report any other bugs in the future. For now I am closing this issue.
