### ISSUE TITLE
Cannot rerun root digger with same line of code

### ISSUE THREAD

**Issue by jamiethompson77** [computations/root_digger#4]
Hiya,
 I ran root digger successfully, but didn't tell it to output to a file and my tree is very big, so in the log I am missing a lot of it.  So I tried to run it again with exactly the same code (but asking it to write to file).  This is the error code.
[0.00] [Warning] Loading options from the checkpoint file
...
[2.24] [Warning] The number of searches is less than the number of processes. Some nodes will do no work
There was an error during processing:
Indicies were not assigned before calling optimizations functions

Best wishes,
Jamie

**Comment by computations** [comment]
Hello Jamie,

Thanks for the bug report. Could you send the full log, checkpoint file, the alignment and the tree to me (via email, if you are able). 

For now, since you have a checkpoint with the finished results, you can just dispatch the job with 1 process and it will print the final tree. 

Best,
Ben
